use std::collections::HashSet;

use anyhow::{Context, Result, bail};
use serde::Serialize;
use serde_json::Value;

#[derive(Serialize)]
pub struct Counts {
    pub provider: usize,
    pub resource_schemas: usize,
    pub data_source_schemas: usize,
    pub ephemeral_resource_schemas: usize,
    pub functions: usize,
}

pub fn render_provider(
    provider_path: &str,
    source: &str,
    version: &str,
    schema: &Value,
    schema_sha256: &str,
) -> Result<(String, Counts)> {
    let package = package_name(provider_path);
    let mut lines = vec![
        "// Copyright 2026 David Flanagan".to_owned(),
        "// Generated by pulumi-cue; do not edit.".to_owned(),
        format!("// Terraform provider {source} version {version}."),
        format!("// Source schema SHA-256: {schema_sha256}"),
        format!("package {package}"),
        String::new(),
    ];
    let mut definitions = HashSet::new();
    let mut uses_list_constraints = false;
    let provider_schema = schema
        .get("provider")
        .and_then(Value::as_object)
        .context("Terraform provider schema is missing the provider block")?;
    render_block_definition(
        "#ProviderConfig",
        provider_schema,
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    lines.push(String::new());

    let resource_schemas = category(schema, "resource_schemas")?;
    let data_source_schemas = category(schema, "data_source_schemas")?;
    let ephemeral_schemas = category(schema, "ephemeral_resource_schemas")?;
    let functions = category(schema, "functions")?;

    render_schema_map(
        resource_schemas,
        "Resource",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_schema_map(
        data_source_schemas,
        "DataSource",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_schema_map(
        ephemeral_schemas,
        "EphemeralResource",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_functions(functions, &mut definitions, &mut lines)?;

    for (key, value) in schema
        .as_object()
        .context("provider schema must be an object")?
    {
        if key.ends_with("_schemas")
            && !matches!(
                key.as_str(),
                "resource_schemas" | "data_source_schemas" | "ephemeral_resource_schemas"
            )
            && value.is_object()
        {
            bail!("Terraform returned an unhandled schema category {key:?}");
        }
    }
    if uses_list_constraints {
        lines.insert(5, "import \"list\"".to_owned());
    }

    let counts = Counts {
        provider: 1,
        resource_schemas: resource_schemas.len(),
        data_source_schemas: data_source_schemas.len(),
        ephemeral_resource_schemas: ephemeral_schemas.len(),
        functions: functions.len(),
    };
    Ok((lines.join("\n").trim_end().to_owned() + "\n", counts))
}

fn category<'a>(schema: &'a Value, name: &str) -> Result<&'a serde_json::Map<String, Value>> {
    match schema.get(name) {
        None | Some(Value::Null) => Ok(empty_object()),
        Some(value) => value
            .as_object()
            .with_context(|| format!("Terraform schema category {name:?} must be an object")),
    }
}

fn empty_object() -> &'static serde_json::Map<String, Value> {
    static EMPTY: std::sync::OnceLock<serde_json::Map<String, Value>> = std::sync::OnceLock::new();
    EMPTY.get_or_init(serde_json::Map::new)
}

fn render_schema_map(
    schemas: &serde_json::Map<String, Value>,
    prefix: &str,
    definitions: &mut HashSet<String>,
    uses_list_constraints: &mut bool,
    lines: &mut Vec<String>,
) -> Result<()> {
    for (name, schema) in schemas {
        let definition = cue_definition_name(prefix, name);
        let block = schema
            .as_object()
            .with_context(|| format!("schema {name:?} must be an object"))?;
        render_block_definition(
            &definition,
            block,
            definitions,
            uses_list_constraints,
            lines,
        )?;
        lines.push(String::new());
    }
    Ok(())
}

fn render_block_definition(
    name: &str,
    schema: &serde_json::Map<String, Value>,
    definitions: &mut HashSet<String>,
    uses_list_constraints: &mut bool,
    lines: &mut Vec<String>,
) -> Result<()> {
    if !definitions.insert(name.to_owned()) {
        bail!("Terraform names collide after conversion to CUE definition {name}");
    }
    let block = schema
        .get("block")
        .and_then(Value::as_object)
        .with_context(|| format!("schema {name} does not contain a block object"))?;
    let fields = render_fields(block, uses_list_constraints)?;
    lines.push(format!("{name}: {{"));
    lines.extend(fields.into_iter().map(|field| format!("    {field}")));
    lines.push("}".to_owned());
    Ok(())
}

fn render_fields(
    block: &serde_json::Map<String, Value>,
    uses_list_constraints: &mut bool,
) -> Result<Vec<String>> {
    let attributes = block
        .get("attributes")
        .map(as_object("attributes"))
        .transpose()?
        .cloned()
        .unwrap_or_default();
    let block_types = block
        .get("block_types")
        .map(as_object("block_types"))
        .transpose()?
        .cloned()
        .unwrap_or_default();
    let mut fields = Vec::new();
    let mut names = HashSet::new();

    for (name, attribute) in &attributes {
        let attribute = attribute
            .as_object()
            .with_context(|| format!("Terraform attribute {name:?} must be an object"))?;
        if !input_attribute(name, attribute)? {
            continue;
        }
        let required = bool_field(attribute, "required")?.unwrap_or(false);
        let value = render_attribute(attribute, uses_list_constraints)
            .with_context(|| format!("attribute {name:?}"))?;
        push_field(&mut fields, &mut names, name, required, &value)?;
    }

    for (name, nested) in &block_types {
        let nested = nested
            .as_object()
            .with_context(|| format!("Terraform block type {name:?} must be an object"))?;
        let mode = string_field(nested, "nesting_mode")?.unwrap_or("single");
        let block = nested
            .get("block")
            .and_then(Value::as_object)
            .with_context(|| format!("Terraform block type {name:?} has no block object"))?;
        let value = render_block_type(block, uses_list_constraints)?;
        let min = bound(nested.get("min_items"), 0, "min_items")?;
        let max = optional_bound(nested.get("max_items"), "max_items")?;
        let value = match mode {
            "list" | "set" => render_list_type(&value, min, max, uses_list_constraints)?,
            "map" => format!("{{[string]: {value}}}"),
            "single" => value,
            other => bail!("unsupported Terraform block nesting mode {other:?}"),
        };
        push_field(&mut fields, &mut names, name, min > 0, &value)?;
    }
    Ok(fields)
}

fn input_attribute(name: &str, attribute: &serde_json::Map<String, Value>) -> Result<bool> {
    let keys = ["required", "optional", "computed", "write_only"];
    if keys.iter().all(|key| !attribute.contains_key(*key)) {
        bail!("Terraform attribute {name:?} is missing required/optional/computed metadata");
    }
    let required = bool_field(attribute, "required")?.unwrap_or(false);
    let optional = bool_field(attribute, "optional")?.unwrap_or(false);
    let write_only = bool_field(attribute, "write_only")?.unwrap_or(false);
    if required && optional {
        bail!("Terraform attribute {name:?} is both required and optional");
    }
    Ok(required || optional || write_only)
}

fn render_attribute(
    attribute: &serde_json::Map<String, Value>,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    let value = match attribute.get("nested_type") {
        Some(Value::Null) | None => render_type(attribute.get("type").context("missing type")?)?,
        Some(nested) => render_nested_type(
            nested
                .as_object()
                .context("nested_type must be an object")?,
            uses_list_constraints,
        )?,
    };
    if bool_field(attribute, "required")?.unwrap_or(false) {
        Ok(value)
    } else {
        Ok(format!("{value} | null"))
    }
}

fn render_nested_type(
    nested: &serde_json::Map<String, Value>,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    let mode = string_field(nested, "nesting_mode")?.unwrap_or("single");
    let object = serde_json::Map::from_iter([
        (
            "attributes".to_owned(),
            nested
                .get("attributes")
                .cloned()
                .unwrap_or(Value::Object(serde_json::Map::new())),
        ),
        (
            "block_types".to_owned(),
            nested
                .get("block_types")
                .cloned()
                .unwrap_or(Value::Object(serde_json::Map::new())),
        ),
    ]);
    let value = render_block_type(&object, uses_list_constraints)?;
    match mode {
        "list" | "set" => render_list_type(
            &value,
            bound(nested.get("min_items"), 0, "min_items")?,
            optional_bound(nested.get("max_items"), "max_items")?,
            uses_list_constraints,
        ),
        "map" => Ok(format!("{{[string]: {value}}}")),
        "single" => Ok(value),
        other => bail!("unsupported Terraform nested type mode {other:?}"),
    }
}

fn render_block_type(
    block: &serde_json::Map<String, Value>,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    let fields = render_fields(block, uses_list_constraints)?;
    if fields.is_empty() {
        Ok("{}".to_owned())
    } else {
        Ok(format!("{{ {} }}", fields.join(", ")))
    }
}

fn render_type(value: &Value) -> Result<String> {
    match value {
        Value::String(kind) => match kind.as_str() {
            "bool" => Ok("bool".to_owned()),
            "dynamic" => Ok("_".to_owned()),
            "number" => Ok("number".to_owned()),
            "string" => Ok("string".to_owned()),
            other => bail!("unsupported Terraform type {other:?}"),
        },
        Value::Array(values) if !values.is_empty() => {
            let kind = values[0]
                .as_str()
                .context("Terraform collection type name must be a string")?;
            match kind {
                "list" | "set" if values.len() == 2 => {
                    Ok(format!("[...({})]", nullable(&render_type(&values[1])?)))
                }
                "map" if values.len() == 2 => Ok(format!(
                    "{{[string]: {}}}",
                    nullable(&render_type(&values[1])?)
                )),
                "tuple" if values.len() == 2 => {
                    let elements = values[1]
                        .as_array()
                        .context("Terraform tuple type must contain an array")?;
                    Ok(format!(
                        "[{}]",
                        elements
                            .iter()
                            .map(|value| render_type(value).map(|value| nullable(&value)))
                            .collect::<Result<Vec<_>>>()?
                            .join(", ")
                    ))
                }
                "object" if values.len() == 2 => {
                    let fields = values[1]
                        .as_object()
                        .context("Terraform object type must contain an object")?;
                    let mut rendered = Vec::new();
                    for (name, value) in fields {
                        rendered.push(format!(
                            "{}!: {}",
                            cue_label(name)?,
                            nullable(&render_type(value)?)
                        ));
                    }
                    if rendered.is_empty() {
                        Ok("{}".to_owned())
                    } else {
                        Ok(format!("{{ {} }}", rendered.join(", ")))
                    }
                }
                "dynamic" if values.len() == 1 => Ok("_".to_owned()),
                _ => bail!("unsupported Terraform type representation {value}"),
            }
        }
        _ => bail!("unsupported Terraform type representation {value}"),
    }
}

fn render_list_type(
    element_type: &str,
    minimum: usize,
    maximum: Option<usize>,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    if maximum.is_some_and(|maximum| maximum < minimum) {
        bail!("invalid Terraform list bounds: min={minimum}, max={maximum:?}");
    }
    if minimum == 0 && maximum.is_none() {
        return Ok(format!("[...{element_type}]"));
    }
    *uses_list_constraints = true;
    let mut constraints = vec![format!("[...{element_type}]")];
    if minimum > 0 {
        constraints.push(format!("list.MinItems({minimum})"));
    }
    if let Some(maximum) = maximum {
        constraints.push(format!("list.MaxItems({maximum})"));
    }
    Ok(constraints.join(" & "))
}

fn render_functions(
    functions: &serde_json::Map<String, Value>,
    definitions: &mut HashSet<String>,
    lines: &mut Vec<String>,
) -> Result<()> {
    for (name, function) in functions {
        let definition = cue_definition_name("Function", name);
        if !definitions.insert(definition.clone()) {
            bail!("Terraform names collide after conversion to CUE definition {definition}");
        }
        let function = function
            .as_object()
            .with_context(|| format!("Terraform function {name:?} must be an object"))?;
        let parameters = match function.get("parameters") {
            None | Some(Value::Null) => Vec::new(),
            Some(value) => value
                .as_array()
                .context("Terraform function parameters must be an array")?
                .clone(),
        };
        let mut arguments = Vec::new();
        for parameter in parameters {
            arguments.push(render_parameter(&parameter)?);
        }
        if let Some(variadic) = function.get("variadic_parameter") {
            if !variadic.is_null() {
                arguments.push(format!("...({})", render_parameter(variadic)?));
            }
        }
        let return_type = render_type(
            function
                .get("return_type")
                .context("function missing return_type")?,
        )?;
        lines.push(format!("{definition}: {{"));
        lines.push(format!("    arguments: [{}]", arguments.join(", ")));
        lines.push(format!("    returns: {return_type}"));
        lines.push("}".to_owned());
        lines.push(String::new());
    }
    Ok(())
}

fn render_parameter(parameter: &Value) -> Result<String> {
    let parameter = parameter
        .as_object()
        .context("Terraform function parameter must be an object")?;
    let mut result = render_type(parameter.get("type").context("parameter missing type")?)?;
    if bool_field(parameter, "is_nullable")?.unwrap_or(false) {
        result = nullable(&result);
    }
    Ok(result)
}

fn cue_definition_name(prefix: &str, name: &str) -> String {
    let suffix: String = name
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect();
    let suffix = if suffix.is_empty()
        || suffix
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_digit())
    {
        format!("_{suffix}")
    } else {
        suffix
    };
    format!("#{prefix}_{suffix}")
}

pub fn package_name(provider_path: &str) -> String {
    let last = provider_path.rsplit('/').next().unwrap_or("provider");
    let sanitized: String = last
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect();
    if sanitized
        .chars()
        .next()
        .is_some_and(|character| !character.is_ascii_alphabetic())
    {
        format!("provider_{sanitized}")
    } else {
        sanitized
    }
}

fn cue_label(name: &str) -> Result<String> {
    Ok(serde_json::to_string(name)?)
}

fn nullable(value: &str) -> String {
    format!("({value} | null)")
}

fn push_field(
    fields: &mut Vec<String>,
    names: &mut HashSet<String>,
    name: &str,
    required: bool,
    value: &str,
) -> Result<()> {
    if !names.insert(name.to_owned()) {
        bail!("Terraform block repeats field name {name:?}");
    }
    let marker = if required { "!" } else { "?" };
    fields.push(format!("{}{marker}: {value}", cue_label(name)?));
    Ok(())
}

fn bool_field(object: &serde_json::Map<String, Value>, name: &str) -> Result<Option<bool>> {
    match object.get(name) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => value
            .as_bool()
            .map(Some)
            .with_context(|| format!("Terraform schema field {name:?} must be boolean")),
    }
}

fn string_field<'a>(
    object: &'a serde_json::Map<String, Value>,
    name: &str,
) -> Result<Option<&'a str>> {
    match object.get(name) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => value
            .as_str()
            .map(Some)
            .with_context(|| format!("Terraform schema field {name:?} must be a string")),
    }
}

fn bound(value: Option<&Value>, default: usize, name: &str) -> Result<usize> {
    match value {
        None | Some(Value::Null) => Ok(default),
        Some(value) => value
            .as_u64()
            .and_then(|number| usize::try_from(number).ok())
            .with_context(|| {
                format!("Terraform schema field {name:?} must be a non-negative integer")
            }),
    }
}

fn optional_bound(value: Option<&Value>, name: &str) -> Result<Option<usize>> {
    match value {
        None | Some(Value::Null) => Ok(None),
        Some(value) => bound(Some(value), 0, name).map(Some),
    }
}

fn as_object(name: &'static str) -> impl FnOnce(&Value) -> Result<&serde_json::Map<String, Value>> {
    move |value| {
        value
            .as_object()
            .with_context(|| format!("Terraform schema field {name:?} must be an object"))
    }
}
