use std::collections::HashMap;

use anyhow::{Context, Result, bail};
use serde::Serialize;
use serde_json::Value;

#[derive(Serialize)]
pub struct Counts {
    pub provider: usize,
    pub resource_schemas: usize,
    pub data_source_schemas: usize,
    pub ephemeral_resource_schemas: usize,
    pub list_resource_schemas: usize,
    pub action_schemas: usize,
    pub resource_identity_schemas: usize,
    pub state_store_schemas: usize,
    pub functions: usize,
}

pub fn render_provider(
    provider_path: &str,
    source: &str,
    version: &str,
    schema: &Value,
    schema_sha256: &str,
) -> Result<(String, Counts)> {
    let package = package_name(provider_path);
    let mut lines = vec![
        "// Copyright 2026 David Flanagan".to_owned(),
        "// Generated by terraform-cue; do not edit.".to_owned(),
        format!("// Terraform provider {source} version {version}."),
        format!("// Source schema SHA-256: {schema_sha256}"),
        format!("package {package}"),
        String::new(),
    ];
    let mut definitions = HashMap::new();
    let mut uses_list_constraints = false;
    let provider_schema = schema
        .get("provider")
        .and_then(Value::as_object)
        .context("Terraform provider schema is missing the provider block")?;
    render_block_definition(
        "#ProviderConfig",
        Some("provider"),
        "provider configuration",
        provider_schema,
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    lines.push(String::new());

    let resource_schemas = category(schema, "resource_schemas")?;
    let data_source_schemas = category(schema, "data_source_schemas")?;
    let ephemeral_schemas = category(schema, "ephemeral_resource_schemas")?;
    let list_resource_schemas = category(schema, "list_resource_schemas")?;
    let action_schemas = category(schema, "action_schemas")?;
    let resource_identity_schemas = category(schema, "resource_identity_schemas")?;
    let state_store_schemas = category(schema, "state_store_schemas")?;
    let functions = category(schema, "functions")?;

    render_schema_map(
        resource_schemas,
        "Resource",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_schema_map(
        data_source_schemas,
        "DataSource",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_schema_map(
        ephemeral_schemas,
        "EphemeralResource",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_schema_map(
        list_resource_schemas,
        "ListResource",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_schema_map(
        action_schemas,
        "Action",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_identity_schemas(resource_identity_schemas, &mut definitions, &mut lines)?;
    render_schema_map(
        state_store_schemas,
        "StateStore",
        &mut definitions,
        &mut uses_list_constraints,
        &mut lines,
    )?;
    render_functions(functions, &mut definitions, &mut lines)?;

    for (key, value) in schema
        .as_object()
        .context("provider schema must be an object")?
    {
        if key.ends_with("_schemas")
            && !matches!(
                key.as_str(),
                "resource_schemas"
                    | "data_source_schemas"
                    | "ephemeral_resource_schemas"
                    | "list_resource_schemas"
                    | "action_schemas"
                    | "resource_identity_schemas"
                    | "state_store_schemas"
            )
            && value.is_object()
        {
            bail!("Terraform returned an unhandled schema category {key:?}");
        }
    }
    if uses_list_constraints {
        lines.insert(5, "import \"list\"".to_owned());
    }

    let counts = Counts {
        provider: 1,
        resource_schemas: resource_schemas.len(),
        data_source_schemas: data_source_schemas.len(),
        ephemeral_resource_schemas: ephemeral_schemas.len(),
        list_resource_schemas: list_resource_schemas.len(),
        action_schemas: action_schemas.len(),
        resource_identity_schemas: resource_identity_schemas.len(),
        state_store_schemas: state_store_schemas.len(),
        functions: functions.len(),
    };
    Ok((lines.join("\n").trim_end().to_owned() + "\n", counts))
}

fn category<'a>(schema: &'a Value, name: &str) -> Result<&'a serde_json::Map<String, Value>> {
    match schema.get(name) {
        None | Some(Value::Null) => Ok(empty_object()),
        Some(value) => value
            .as_object()
            .with_context(|| format!("Terraform schema category {name:?} must be an object")),
    }
}

fn empty_object() -> &'static serde_json::Map<String, Value> {
    static EMPTY: std::sync::OnceLock<serde_json::Map<String, Value>> = std::sync::OnceLock::new();
    EMPTY.get_or_init(serde_json::Map::new)
}

fn render_schema_map(
    schemas: &serde_json::Map<String, Value>,
    prefix: &str,
    definitions: &mut HashMap<String, String>,
    uses_list_constraints: &mut bool,
    lines: &mut Vec<String>,
) -> Result<()> {
    if schemas.is_empty() {
        return Ok(());
    }
    let mut names = HashMap::new();
    let mut members = Vec::with_capacity(schemas.len());
    for (name, schema) in schemas {
        let cue_name = pascal_case(name)?;
        register_name(&mut names, &cue_name, name, prefix)?;
        let definition = cue_definition_name(prefix, name)?;
        let block = schema
            .as_object()
            .with_context(|| format!("schema {name:?} must be an object"))?;
        render_block_definition(
            &definition,
            Some(name),
            &format!("{prefix}.{name}"),
            block,
            definitions,
            uses_list_constraints,
            lines,
        )?;
        members.push(format!("    {}: {definition}", cue_label(&cue_name)?));
        lines.push(String::new());
    }
    lines.push(format!("{prefix}: {{"));
    lines.extend(members);
    lines.push("}".to_owned());
    lines.push(String::new());
    Ok(())
}

fn render_identity_schemas(
    schemas: &serde_json::Map<String, Value>,
    definitions: &mut HashMap<String, String>,
    lines: &mut Vec<String>,
) -> Result<()> {
    if schemas.is_empty() {
        return Ok(());
    }
    let mut names = HashMap::new();
    let mut members = Vec::with_capacity(schemas.len());
    for (name, schema) in schemas {
        let cue_name = pascal_case(name)?;
        register_name(&mut names, &cue_name, name, "ResourceIdentity")?;
        let definition = cue_definition_name("ResourceIdentity", name)?;
        let schema = schema
            .as_object()
            .with_context(|| format!("resource identity schema {name:?} must be an object"))?;
        let attributes = schema
            .get("attributes")
            .map(as_object("identity attributes"))
            .transpose()?
            .cloned()
            .unwrap_or_default();
        let mut fields = Vec::new();
        let mut field_names = HashMap::new();
        let schema_path = format!("ResourceIdentity.{name}");

        for (attribute_name, attribute) in &attributes {
            let attribute = attribute.as_object().with_context(|| {
                format!("identity attribute {attribute_name:?} must be an object")
            })?;
            let required_for_import =
                bool_field(attribute, "required_for_import")?.unwrap_or(false);
            let optional_for_import =
                bool_field(attribute, "optional_for_import")?.unwrap_or(false);
            if required_for_import == optional_for_import {
                bail!(
                    "identity attribute {attribute_name:?} must set exactly one of required_for_import or optional_for_import"
                );
            }
            let field_path = format!("{schema_path}.{attribute_name}");
            let value = render_type(
                attribute.get("type").with_context(|| {
                    format!("identity attribute {attribute_name:?} is missing type")
                })?,
                &field_path,
            )?;
            let value = if optional_for_import {
                format!("{value} | null")
            } else {
                value
            };
            push_field(
                &mut fields,
                &mut field_names,
                attribute_name,
                &schema_path,
                required_for_import,
                &value,
            )?;
        }

        insert_definition(definitions, &definition, &schema_path)?;
        lines.push(format!("{definition}: {{"));
        lines.push(format!("    {}", terraform_attribute(name)?));
        lines.extend(fields.into_iter().map(|field| format!("    {field}")));
        lines.push("}".to_owned());
        lines.push(String::new());
        members.push(format!("    {}: {definition}", cue_label(&cue_name)?));
    }
    lines.push("ResourceIdentity: {".to_owned());
    lines.extend(members);
    lines.push("}".to_owned());
    lines.push(String::new());
    Ok(())
}

fn render_block_definition(
    name: &str,
    terraform_name: Option<&str>,
    schema_path: &str,
    schema: &serde_json::Map<String, Value>,
    definitions: &mut HashMap<String, String>,
    uses_list_constraints: &mut bool,
    lines: &mut Vec<String>,
) -> Result<()> {
    insert_definition(definitions, name, schema_path)?;
    let Some(block) = schema.get("block").and_then(Value::as_object) else {
        bail!("schema {name} does not contain a block object");
    };
    let fields = render_fields(block, schema_path, uses_list_constraints)?;
    lines.push(format!("{name}: {{"));
    if let Some(terraform_name) = terraform_name {
        lines.push(format!("    {}", terraform_attribute(terraform_name)?));
    }
    lines.extend(fields.into_iter().map(|field| format!("    {field}")));
    lines.push("}".to_owned());
    Ok(())
}

fn render_fields(
    block: &serde_json::Map<String, Value>,
    schema_path: &str,
    uses_list_constraints: &mut bool,
) -> Result<Vec<String>> {
    let attributes = block
        .get("attributes")
        .map(as_object("attributes"))
        .transpose()?
        .cloned()
        .unwrap_or_default();
    let block_types = block
        .get("block_types")
        .map(as_object("block_types"))
        .transpose()?
        .cloned()
        .unwrap_or_default();
    let mut fields = Vec::new();
    let mut names = HashMap::new();

    for (name, attribute) in &attributes {
        let attribute = attribute
            .as_object()
            .with_context(|| format!("Terraform attribute {name:?} must be an object"))?;
        if !input_attribute(name, attribute)? {
            continue;
        }
        let field_path = format!("{schema_path}.{name}");
        let required = bool_field(attribute, "required")?.unwrap_or(false);
        let value = render_attribute(attribute, &field_path, uses_list_constraints)
            .with_context(|| format!("attribute {field_path:?}"))?;
        push_field(&mut fields, &mut names, name, schema_path, required, &value)?;
    }

    for (name, nested) in &block_types {
        let nested = nested
            .as_object()
            .with_context(|| format!("Terraform block type {name:?} must be an object"))?;
        let mode = string_field(nested, "nesting_mode")?.unwrap_or("single");
        let field_path = format!("{schema_path}.{name}");
        let block = nested
            .get("block")
            .and_then(Value::as_object)
            .with_context(|| format!("Terraform block type {name:?} has no block object"))?;
        let value = render_block_type(block, &field_path, uses_list_constraints)?;
        let min = bound(nested.get("min_items"), 0, "min_items")?;
        let max = optional_bound(nested.get("max_items"), "max_items")?;
        let value = match mode {
            "list" | "set" => render_list_type(&value, min, max, uses_list_constraints)?,
            "map" => format!("{{[string]: {value}}}"),
            "single" => value,
            other => bail!("unsupported Terraform block nesting mode {other:?}"),
        };
        push_field(&mut fields, &mut names, name, schema_path, min > 0, &value)?;
    }
    Ok(fields)
}

fn input_attribute(name: &str, attribute: &serde_json::Map<String, Value>) -> Result<bool> {
    let keys = ["required", "optional", "computed", "write_only"];
    if keys.iter().all(|key| !attribute.contains_key(*key)) {
        bail!("Terraform attribute {name:?} is missing required/optional/computed metadata");
    }
    let required = bool_field(attribute, "required")?.unwrap_or(false);
    let optional = bool_field(attribute, "optional")?.unwrap_or(false);
    let write_only = bool_field(attribute, "write_only")?.unwrap_or(false);
    if required && optional {
        bail!("Terraform attribute {name:?} is both required and optional");
    }
    Ok(required || optional || write_only)
}

fn render_attribute(
    attribute: &serde_json::Map<String, Value>,
    path: &str,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    let value = match attribute.get("nested_type") {
        Some(Value::Null) | None => {
            render_type(attribute.get("type").context("missing type")?, path)?
        }
        Some(nested) => render_nested_type(
            nested
                .as_object()
                .context("nested_type must be an object")?,
            path,
            uses_list_constraints,
        )?,
    };
    if bool_field(attribute, "required")?.unwrap_or(false) {
        Ok(value)
    } else {
        Ok(format!("{value} | null"))
    }
}

fn render_nested_type(
    nested: &serde_json::Map<String, Value>,
    path: &str,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    let mode = string_field(nested, "nesting_mode")?.unwrap_or("single");
    let object = serde_json::Map::from_iter([
        (
            "attributes".to_owned(),
            nested
                .get("attributes")
                .cloned()
                .unwrap_or(Value::Object(serde_json::Map::new())),
        ),
        (
            "block_types".to_owned(),
            nested
                .get("block_types")
                .cloned()
                .unwrap_or(Value::Object(serde_json::Map::new())),
        ),
    ]);
    let value = render_block_type(&object, path, uses_list_constraints)?;
    match mode {
        "list" | "set" => render_list_type(
            &value,
            bound(nested.get("min_items"), 0, "min_items")?,
            optional_bound(nested.get("max_items"), "max_items")?,
            uses_list_constraints,
        ),
        "map" => Ok(format!("{{[string]: {value}}}")),
        "single" => Ok(value),
        other => bail!("unsupported Terraform nested type mode {other:?}"),
    }
}

fn render_block_type(
    block: &serde_json::Map<String, Value>,
    path: &str,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    let fields = render_fields(block, path, uses_list_constraints)?;
    if fields.is_empty() {
        Ok("{}".to_owned())
    } else {
        Ok(format!("{{ {} }}", fields.join(", ")))
    }
}

fn render_type(value: &Value, path: &str) -> Result<String> {
    match value {
        Value::String(kind) => match kind.as_str() {
            "bool" => Ok("bool".to_owned()),
            "dynamic" => Ok("_".to_owned()),
            "number" => Ok("number".to_owned()),
            "string" => Ok("string".to_owned()),
            other => bail!("unsupported Terraform type {other:?}"),
        },
        Value::Array(values) if !values.is_empty() => {
            let kind = values[0]
                .as_str()
                .context("Terraform collection type name must be a string")?;
            match kind {
                "list" | "set" if values.len() == 2 => Ok(format!(
                    "[...({})]",
                    nullable(&render_type(&values[1], &format!("{path}[]"))?)
                )),
                "map" if values.len() == 2 => Ok(format!(
                    "{{[string]: {}}}",
                    nullable(&render_type(&values[1], &format!("{path}[*]"))?)
                )),
                "tuple" if values.len() == 2 => {
                    let elements = values[1]
                        .as_array()
                        .context("Terraform tuple type must contain an array")?;
                    Ok(format!(
                        "[{}]",
                        elements
                            .iter()
                            .enumerate()
                            .map(|(index, value)| {
                                render_type(value, &format!("{path}[{index}]"))
                                    .map(|value| nullable(&value))
                            })
                            .collect::<Result<Vec<_>>>()?
                            .join(", ")
                    ))
                }
                "object" if values.len() == 2 => {
                    let fields = values[1]
                        .as_object()
                        .context("Terraform object type must contain an object")?;
                    let mut rendered = Vec::new();
                    let mut names = HashMap::new();
                    for (name, value) in fields {
                        let field_path = format!("{path}.{name}");
                        let cue_name = camel_case(name, false).with_context(|| {
                            format!("convert Terraform object field {field_path:?}")
                        })?;
                        register_name(
                            &mut names,
                            &cue_name,
                            name,
                            &format!("object fields in {path}"),
                        )?;
                        rendered.push(format!(
                            "{}!: {} {}",
                            cue_label(&cue_name)?,
                            nullable(&render_type(value, &field_path)?),
                            terraform_attribute(name)?,
                        ));
                    }
                    if rendered.is_empty() {
                        Ok("{}".to_owned())
                    } else {
                        Ok(format!("{{ {} }}", rendered.join(", ")))
                    }
                }
                "dynamic" if values.len() == 1 => Ok("_".to_owned()),
                _ => bail!("unsupported Terraform type representation {value}"),
            }
        }
        _ => bail!("unsupported Terraform type representation {value}"),
    }
}

fn render_list_type(
    element_type: &str,
    minimum: usize,
    maximum: Option<usize>,
    uses_list_constraints: &mut bool,
) -> Result<String> {
    if maximum.is_some_and(|maximum| maximum < minimum) {
        bail!("invalid Terraform list bounds: min={minimum}, max={maximum:?}");
    }
    if minimum == 0 && maximum.is_none() {
        return Ok(format!("[...{element_type}]"));
    }
    *uses_list_constraints = true;
    let mut constraints = vec![format!("[...{element_type}]")];
    if minimum > 0 {
        constraints.push(format!("list.MinItems({minimum})"));
    }
    if let Some(maximum) = maximum {
        constraints.push(format!("list.MaxItems({maximum})"));
    }
    Ok(constraints.join(" & "))
}

fn render_functions(
    functions: &serde_json::Map<String, Value>,
    definitions: &mut HashMap<String, String>,
    lines: &mut Vec<String>,
) -> Result<()> {
    let mut names = HashMap::new();
    let mut members = Vec::with_capacity(functions.len());
    for (name, function) in functions {
        let cue_name = pascal_case(name)?;
        register_name(&mut names, &cue_name, name, "Function")?;
        let definition = cue_definition_name("Function", name)?;
        let function = function
            .as_object()
            .with_context(|| format!("Terraform function {name:?} must be an object"))?;
        let parameters = match function.get("parameters") {
            None | Some(Value::Null) => Vec::new(),
            Some(value) => value
                .as_array()
                .context("Terraform function parameters must be an array")?
                .clone(),
        };
        let mut arguments = Vec::new();
        for (index, parameter) in parameters.iter().enumerate() {
            arguments.push(render_parameter(
                parameter,
                &format!("function {name} argument {index}"),
            )?);
        }
        if let Some(variadic) = function.get("variadic_parameter") {
            if !variadic.is_null() {
                arguments.push(format!(
                    "...({})",
                    render_parameter(variadic, &format!("function {name} variadic argument"))?
                ));
            }
        }
        let return_type = render_type(
            function
                .get("return_type")
                .context("function missing return_type")?,
            &format!("function {name} return"),
        )?;
        insert_definition(definitions, &definition, &format!("Function.{name}"))?;
        lines.push(format!("{definition}: {{"));
        lines.push(format!("    {}", terraform_attribute(name)?));
        lines.push(format!("    arguments: [{}]", arguments.join(", ")));
        lines.push(format!("    returns: {return_type}"));
        lines.push("}".to_owned());
        lines.push(String::new());
        members.push(format!("    {}: {definition}", cue_label(&cue_name)?));
    }
    lines.push("Function: {".to_owned());
    lines.extend(members);
    lines.push("}".to_owned());
    lines.push(String::new());
    Ok(())
}

fn render_parameter(parameter: &Value, path: &str) -> Result<String> {
    let parameter = parameter
        .as_object()
        .context("Terraform function parameter must be an object")?;
    let mut result = render_type(
        parameter.get("type").context("parameter missing type")?,
        path,
    )?;
    if bool_field(parameter, "is_nullable")?.unwrap_or(false) {
        result = nullable(&result);
    }
    Ok(result)
}

fn cue_definition_name(prefix: &str, name: &str) -> Result<String> {
    Ok(format!("_#{prefix}Schema{}", pascal_case(name)?))
}

fn pascal_case(name: &str) -> Result<String> {
    camel_case(name, true)
}

fn camel_case(name: &str, uppercase_first: bool) -> Result<String> {
    let words = name
        .split(|character: char| !character.is_alphanumeric())
        .filter(|word| !word.is_empty());
    let mut result = String::new();
    for (index, word) in words.enumerate() {
        if index == 0 {
            result.push_str(&lower_camel_word(word));
        } else {
            result.push_str(&title_word(word));
        }
    }
    if result.is_empty() {
        bail!("Terraform name {name:?} has no alphanumeric characters");
    }
    if uppercase_first {
        result = capitalize_first(&result);
    }
    Ok(result)
}

fn lower_camel_word(word: &str) -> String {
    let characters: Vec<char> = word.chars().collect();
    let uppercase_prefix = characters
        .iter()
        .take_while(|character| character.is_uppercase())
        .count();
    let next_is_lowercase = characters
        .get(uppercase_prefix)
        .is_some_and(|character| character.is_lowercase());
    let lowercase_count = if uppercase_prefix == characters.len() || !next_is_lowercase {
        uppercase_prefix.max(1)
    } else if uppercase_prefix > 1 {
        uppercase_prefix - 1
    } else {
        1
    };

    characters
        .into_iter()
        .enumerate()
        .flat_map(|(index, character)| {
            if index < lowercase_count {
                character.to_lowercase().collect::<Vec<_>>()
            } else {
                vec![character]
            }
        })
        .collect()
}

fn title_word(word: &str) -> String {
    let mut characters = word.chars();
    let Some(first) = characters.next() else {
        return String::new();
    };
    let mut result = first.to_uppercase().collect::<String>();
    result.push_str(&characters.as_str().to_lowercase());
    result
}

fn capitalize_first(word: &str) -> String {
    let mut characters = word.chars();
    let Some(first) = characters.next() else {
        return String::new();
    };
    let mut result = first.to_uppercase().collect::<String>();
    result.push_str(characters.as_str());
    result
}

fn register_name(
    names: &mut HashMap<String, String>,
    cue_name: &str,
    terraform_name: &str,
    scope: &str,
) -> Result<()> {
    if let Some(previous) = names.insert(cue_name.to_owned(), terraform_name.to_owned()) {
        bail!(
            "Terraform {scope} names {previous:?} and {terraform_name:?} collide after case conversion to CUE name {cue_name:?}"
        );
    }
    Ok(())
}

fn insert_definition(
    definitions: &mut HashMap<String, String>,
    definition: &str,
    terraform_name: &str,
) -> Result<()> {
    if let Some(previous) = definitions.insert(definition.to_owned(), terraform_name.to_owned()) {
        bail!(
            "Terraform schema names {previous:?} and {terraform_name:?} collide at CUE definition {definition}"
        );
    }
    Ok(())
}

fn terraform_attribute(name: &str) -> Result<String> {
    Ok(format!("@terraform(name={})", serde_json::to_string(name)?))
}

pub fn package_name(provider_path: &str) -> String {
    let last = provider_path.rsplit('/').next().unwrap_or("provider");
    let sanitized: String = last
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect();
    const RESERVED: &[&str] = &[
        "as", "break", "case", "continue", "default", "else", "false", "for", "func", "if",
        "import", "in", "let", "null", "package", "range", "return", "select", "switch", "true",
        "where", "with",
    ];
    if sanitized
        .chars()
        .next()
        .is_some_and(|character| !character.is_ascii_alphabetic())
        || RESERVED.contains(&sanitized.as_str())
    {
        format!("provider_{sanitized}")
    } else {
        sanitized
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use cuengine::evaluate_cue_package;
    use serde_json::json;
    use tempfile::tempdir;

    use super::{package_name, render_provider};

    #[test]
    fn renders_all_provider_schema_categories() {
        let schema = json!({
            "provider": {"block": {"attributes": {}}},
            "resource_schemas": {
                "widget": {"block": {"attributes": {
                    "name": {"type": "string", "required": true},
                    "display_name": {"type": "string", "optional": true},
                    "settings": {"type": ["object", {
                        "directory_permission": "string"
                    }], "required": true}
                }}}
            },
            "data_source_schemas": {},
            "ephemeral_resource_schemas": {},
            "list_resource_schemas": {
                "widgets": {"block": {"attributes": {
                    "filter": {"type": "string", "optional": true}
                }}}
            },
            "action_schemas": {
                "create_widget": {"block": {"attributes": {
                    "name": {"type": "string", "required": true}
                }}}
            },
            "resource_identity_schemas": {
                "widget": {"attributes": {
                    "id": {"type": "string", "required_for_import": true},
                    "region": {"type": "string", "optional_for_import": true}
                }}
            },
            "state_store_schemas": {
                "remote": {"block": {"attributes": {
                    "endpoint": {"type": "string", "required": true}
                }}}
            },
            "functions": {}
        });
        let (cue, counts) = render_provider(
            "terraform/example/widget",
            "example/widget",
            "1.0.0",
            &schema,
            "hash",
        )
        .expect("all provider schema categories should render");

        assert!(cue.contains("_#ListResourceSchemaWidgets"));
        assert!(cue.contains("_#ActionSchemaCreateWidget"));
        assert!(cue.contains("_#ResourceIdentitySchemaWidget"));
        assert!(cue.contains("\"region\"?: string | null @terraform(name=\"region\")"));
        assert!(cue.contains("_#StateStoreSchemaRemote"));
        assert!(cue.contains("Resource: {"));
        assert!(cue.contains("\"Widget\": _#ResourceSchemaWidget"));
        assert!(cue.contains("\"displayName\"?: string | null @terraform(name=\"display_name\")"));
        assert!(cue.contains(
            "\"directoryPermission\"!: (string | null) @terraform(name=\"directory_permission\")"
        ));
        assert_eq!(counts.list_resource_schemas, 1);
        assert_eq!(counts.action_schemas, 1);
        assert_eq!(counts.resource_identity_schemas, 1);
        assert_eq!(counts.state_store_schemas, 1);

        let directory = tempdir().expect("temporary CUE package directory");
        let module_root = directory.path();
        fs::create_dir_all(module_root.join("cue.mod")).expect("create module metadata directory");
        fs::write(
            module_root.join("cue.mod/module.cue"),
            "module: \"example.com/test@v0\"\nlanguage: version: \"v0.16.0\"\nsource: kind: \"self\"\n",
        )
        .expect("write module metadata");
        fs::write(module_root.join("schema.cue"), cue).expect("write generated schema");
        evaluate_cue_package(module_root, "widget")
            .expect("cuengine should evaluate all generated schema categories");
    }

    #[test]
    fn avoids_reserved_cue_package_names() {
        assert_eq!(package_name("terraform/hashicorp/null"), "provider_null");
    }
}

fn cue_label(name: &str) -> Result<String> {
    Ok(serde_json::to_string(name)?)
}

fn nullable(value: &str) -> String {
    format!("({value} | null)")
}

fn push_field(
    fields: &mut Vec<String>,
    names: &mut HashMap<String, String>,
    name: &str,
    schema_path: &str,
    required: bool,
    value: &str,
) -> Result<()> {
    let cue_name = camel_case(name, false)
        .with_context(|| format!("convert Terraform field {name:?} in {schema_path}"))?;
    register_name(names, &cue_name, name, &format!("fields in {schema_path}"))?;
    let marker = if required { "!" } else { "?" };
    fields.push(format!(
        "{}{marker}: {value} {}",
        cue_label(&cue_name)?,
        terraform_attribute(name)?
    ));
    Ok(())
}

fn bool_field(object: &serde_json::Map<String, Value>, name: &str) -> Result<Option<bool>> {
    match object.get(name) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => value
            .as_bool()
            .map(Some)
            .with_context(|| format!("Terraform schema field {name:?} must be boolean")),
    }
}

fn string_field<'a>(
    object: &'a serde_json::Map<String, Value>,
    name: &str,
) -> Result<Option<&'a str>> {
    match object.get(name) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => value
            .as_str()
            .map(Some)
            .with_context(|| format!("Terraform schema field {name:?} must be a string")),
    }
}

fn bound(value: Option<&Value>, default: usize, name: &str) -> Result<usize> {
    match value {
        None | Some(Value::Null) => Ok(default),
        Some(value) => value
            .as_u64()
            .and_then(|number| usize::try_from(number).ok())
            .with_context(|| {
                format!("Terraform schema field {name:?} must be a non-negative integer")
            }),
    }
}

fn optional_bound(value: Option<&Value>, name: &str) -> Result<Option<usize>> {
    match value {
        None | Some(Value::Null) => Ok(None),
        Some(value) => bound(Some(value), 0, name).map(Some),
    }
}

fn as_object(name: &'static str) -> impl FnOnce(&Value) -> Result<&serde_json::Map<String, Value>> {
    move |value| {
        value
            .as_object()
            .with_context(|| format!("Terraform schema field {name:?} must be an object"))
    }
}
